name: ios_icon_finder
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

  # state management
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.4.10
  hooks_riverpod: ^2.4.10
  riverpod_annotation: null

  # data
  http: ^1.2.1

  # unique 
  uuid: ^4.3.3

  # util
  envied: ^0.5.3
  flextras: ^1.0.0
  separated_row: ^3.0.3
  device_preview: ^1.1.0
  liquid_pull_to_refresh: ^3.0.1

  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # animate list item
  badges: ^3.1.2
  animated_item_action: ^0.0.1
  
dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Gelion
      fonts:
        - asset: assets/fonts/gelion_regular.ttf
        - asset: assets/fonts/gelion_bold.ttf
          weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
