name: Build and Deploy to Output Repo

on:
  push:
    branches:
      - main # Change this to your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Flutter Project
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create .env file
        run: |
          echo "API=${{ secrets.ENV_API_KEY }}" > .env

      - name: Create env source file
        run: |
          mkdir -p lib/services/env
          cat > lib/services/env/m_env.dart << 'EOF'
          import 'package:envied/envied.dart';
          part 'm_env.g.dart';

          @Envied(path: '.env')
          abstract class Env {
            @EnviedField(varName: 'API')
            static const String api = _Env.api;
          }
          EOF

      - name: Generate Envied Code
        # FIX 1: Using 'upgrade' prevents the frontend_server.dart.snapshot error
        run: |
          flutter pub upgrade
          dart run build_runner build --delete-conflicting-outputs

      - name: Build Web
        # FIX 2: Added base-href so GitHub Pages can locate your Javascript and CSS
        run: |
          flutter pub get
          flutter build web --release --base-href "/cupertino_icons_finder_web/" --no-tree-shake-icons

      - name: Restore custom index.html
        run: cp .github/assets/index.html build/web/index.html

      - name: Deploy to Output Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: "build/web"
          destination-github-username: "winminhtetz"
          destination-repository-name: "cupertino_icons_finder_web"
          user-email: "mgwinnminnhtet111@gmail.com"
          target-branch: main
